### ISSUE TITLE
Unlink returns invalid values with Dropbox adapter

### ISSUE THREAD

**Issue by jonathanjfshaw** [twistor/flysystem-stream-wrapper#1]
I've been trying to get Drupal's Flysytem_dropbox to work with Filefield_paths for automatic renaming.

It appears to work out of the box for the local adapter, but for Dropbox it moves the file but does not update Drupal's file entity.

My developers pointed me to the issue that is probably responsible:
"The Dropbox adapter returns a missing value when it deletes a file, from the function delete() at  /public_html/vendor/league/flysystem-dropbox/src/DropboxAdapter.php:154). 
It must return only TRUE or FALSE, since it function is called from FlysystemStreamWrapper::unlink() - 
this it wrapper to php function unlink() which can't return another values." 

They suggest changing that delete() function from:

```
public function delete($path) {
  $location = $this->applyPathPrefix($path);
  return $this->client->delete($location); // it returns full result
}
```

to:

```
public function delete($path) {
    $location = $this->applyPathPrefix($path);
    $result = $this->client->delete($location);
    if (isset($result['is_deleted'])) {
      return $result['is_deleted'];
    }
    return FALSE;
}
```

However, it would seem to me to be better to change the unlink() function in this module. Shouldn't the functions here have their outputs validated to ensure they always return values appropriate for the php functions they are emulating?

At the moment we have:

```
public function unlink($uri)
        {
            $this->uri = $uri;

            return $this->invoke($this->getFilesystem(), 'delete', [$this->getTarget()], 'unlink');
        }
```

Which seems to trust that the Flysystem adapter is only returning values that it would be acceptable for unlink to return, and that is false in the case of the Dropbox adapter.

(Unrelatedly, my developers also tell me that `composer require "guzzle/guzzle:3.x"`  is needed not just the guzzlehttp/guzzle:6.x in Drupal Core, as flysystem_dropbox  uses Url::factory().

**Comment by twistor** [comment]
This should definitely be fixed in flysystem dropbox. It's breaking the interface to return something besides a bool.

Guzzle:3.x is a dependency of the Dropxbox API, so that should be safe. It should probably be changed though, since the Dropbox dependency could change.

**Comment by twistor** [comment]
Pull request created, https://github.com/thephpleague/flysystem-dropbox/pull/8

**Comment by danhunsaker** [comment]
Agreed.  Flysystem adapters are responsible for implementing the Flysystem AdapterInterface, which in turn states that the `delete()` method will return a `boolean` value.  Any adapter which doesn't properly implement an interface is broken - the bug exists at that level.  This project, meanwhile, conforms to the interface properly, by relying on implementations to be properly implemented, and not including extra logic which would allow non-conforming implementations to function, but would in turn violate the interface itself.

**Comment by twistor** [comment]
There's no way to generalize this from the stream wrapper. We could cast to a bool, but then any result from the adapter would be true. We could check for a bool, but then successful values would be seen as false.

**Comment by danhunsaker** [comment]
That too.

**Comment by twistor** [comment]
Issue for Guzzle dependency.

https://www.drupal.org/node/2705003

**Comment by jonathanjfshaw** [comment]
Great, thanks guys
