### ISSUE TITLE
exif_read_data(): File not supported

### ISSUE THREAD

**Issue by arabcoders** [twistor/flysystem-stream-wrapper#10]
Hi,

im not sure why, but exif_read_data is unable to read stream wrapper data as valid file any clues on how to fix it?

**Comment by twistor** [comment]
Off the top of my head, no idea. What's the error?

**Comment by arabcoders** [comment]
hmm, im really not sure my log data says

E_WARNING was triggered.
exif_read_data(): File not supported

/var/app/Resizer.php:161

**Comment by twistor** [comment]
Could be accessing a file that's not jpg or tiff?

**Comment by arabcoders** [comment]
Indeed it was PNG file

**Comment by twistor** [comment]
According to the documentation, only JEPG and TIFF are supported.
