### ISSUE TITLE
is_writable always return false

### ISSUE THREAD

**Issue by SamMousa** [twistor/flysystem-stream-wrapper#5]
For me `is_writable` always returns false because the `uid` and `gid` are always set to `0`.

Currently `Stat::mergeMeta()` ignores any `uid` or `gid` returned from the adapter; would it not make more sense to use them if they are available?

**Comment by twistor** [comment]
I will look into this. Adapters do not return the uid or gid.

**Comment by twistor** [comment]
One option is to pass in a different permission array when registering the stream wrapper.

```php
$options = [
        'permissions' => [
            'dir' => [
                'private' => 0700,
                'public' => 0777,
            ],
            'file' => [
                'private' => 0600,
                'public' => 0666,
            ],
        ],
    ];
```

`FlysystemStreamWrapper::register('fly', $filesystem, $options)`

**Comment by twistor** [comment]
I've added calls to either `posix_getuid()` or `getmyuid()` to set the uid and gid of returned files.
