### ISSUE TITLE
stream_wrapper_register missing STREAM_IS_URL param

### ISSUE THREAD

**Issue by MaximilianKresse** [twistor/flysystem-stream-wrapper#6]
```php
<?php
$sftp = new SftpAdapter([...]);
FlysystemStreamWrapper::register('test', new Filesystem($sftp));

var_dump(ini_get('allow_url_include')); // returns false

include 'test://test.php'; // should trigger the warning - include(): test:// wrapper is disabled in the server configuration by allow_url_include=0
```
The warning isn't triggered but instead the file will be loaded even per sftp.

I think the problem is [here](https://github.com/twistor/flysystem-stream-wrapper/blob/master/src/FlysystemStreamWrapper.php#L171).

[stream_wrapper_register()](http://php.net/manual/de/function.stream-wrapper-register.php) has a third param for flags and flysystem adapters should imho set the flag "STREAM_IS_URL" to prevent loading of php files per stream wrapper when the option [allow_url_include](http://php.net/manual/de/filesystem.configuration.php#ini.allow-url-include) is disabled or at least there should be a pass through parameter for the FlysystemStreamWrapper::register() method (or another configuration option).

**Comment by twistor** [comment]
There's there's a good reason I'm not doing this already, but I can't remember what it is. It should definitely be an option. I would like it by default, but that would break backwards comapt.

**Comment by twistor** [comment]
`FlysystemStreamWrapper::register()` now has a flags parameter.
